In [38]:
import numpy as np
import pandas as pd 

## the Total points for group B in world cup matches:

__Static mode:__

In [37]:
FifaWorldCupGroupB = np.array([[3, 1, 3, 0], [1, 1, 3, 0], [0, 3, 0, 0], [1, 0, 0, 0]])

for i in range(0, 4):
    for j in range(0, 3):
        FifaWorldCupGroupB[i][3] += FifaWorldCupGroupB[i][j]
        
print(FifaWorldCupGroupB)

[[3 1 3 7]
 [1 1 3 5]
 [0 3 0 3]
 [1 0 0 1]]


## Application: The total points for all of teams in each group or league

__Dynamic mode:__

In [163]:
class TableOfTotalPoints():
    
    # By using this function, We're going to assign the total values of each instance to the last column of each row
    def __total_scores(self, *args):
        args = list(args) # convert args to a List of iterables
        for instance in args: # Iterate each intances
            instance.append(0) # Add the total value to each instances  
        
        teams = np.array(args) # Create a 2D array
        # we're using .tolist() or list() to convert numpy.ndarry to a list
        instancesNum = len(teams[:, 0].tolist()) # determine the number of instances
        featuresNum = len(teams[0].tolist()) - 1 # determine the number of features without counting the last column of each row
        lastColIndex = featuresNum # the index of last column of each rows
    
        for i in range(0, instancesNum):
            for j in range(0, featuresNum):
                teams[i,lastColIndex] += teams[i][j]
                
        return teams
    
    
    
    
    def __point_matcher(self, M:np.ndarray):
        li = []
        dic = {'W' : 0 , 'D': 0 , 'L': 0 , 'Pts': np.nan}

        instancesNum = len(M[:, 0].tolist()) 
        featuresNum = len(M[0].tolist()) 

        for i in range(0, instancesNum):
            for j in range(0, featuresNum):
                if j != featuresNum - 1:
                    if M[i, j] == 3:
                         dic['W'] += 1
                    elif M[i, j] == 1:
                        dic['D'] += 1
                    else:
                        dic['L'] += 1
                else:
                    dic['Pts'] = M[i, j]  
            li.append(dic)
            dic = {'W' : 0 , 'D': 0 , 'L': 0 , 'Pts': np.nan}

        return li
    
    
    
    
    def get_table_teams(self, teamNames:list, *args):
        data = {}
        cols = []
        # We should iterate args elements because we can not pass in a tuple or a list of lists to total_scores() function.
        for li in args: # args is a tuple of lists
            cols.append(point_matcher(total_scores(li)))

        for i in range(len(teamNames)):
            data.update({teamNames[i] : cols[i][0]})
        
        df = pd.DataFrame(data).T
        df = df.sort_values(['Pts'], ascending=False)
        return df

In [164]:
table = TableOfTotalPoints()
print(dir(table))

['_TableOfTotalPoints__point_matcher', '_TableOfTotalPoints__total_scores', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'get_table_teams']


As you can see, we can't directly access the total_scores and point_matcher functions, but we can access them using the name mangling process.

In [169]:
table._TableOfTotalPoints__total_scores([1,0,3], [0,0,3], [1,1,1], [3,3,3])

array([[1, 0, 3, 4],
       [0, 0, 3, 3],
       [1, 1, 1, 3],
       [3, 3, 3, 9]])

In [166]:
table._TableOfTotalPoints__total_scores([3, 1, 3, 0], [1, 1, 3, 0], [0, 3, 0, 0], [1, 0, 0, 0])

array([[3, 1, 3, 0, 7],
       [1, 1, 3, 0, 5],
       [0, 3, 0, 0, 3],
       [1, 0, 0, 0, 1]])

In [173]:
table._TableOfTotalPoints__point_matcher(table._TableOfTotalPoints__total_scores([3, 1, 3, 0],
                                                                                 [1, 1, 3, 0],
                                                                                 [0, 3, 0, 0],
                                                                                 [1, 0, 0, 0]))

[{'W': 2, 'D': 1, 'L': 1, 'Pts': 7},
 {'W': 1, 'D': 2, 'L': 1, 'Pts': 5},
 {'W': 1, 'D': 0, 'L': 3, 'Pts': 3},
 {'W': 0, 'D': 1, 'L': 3, 'Pts': 1}]

<br> </br>

In [171]:
table.get_table_teams(['England', 'United States', 'Iran', 'Wales'], [3, 1, 3, 0], [1, 1, 3, 0], [0, 3, 0, 0], [1, 0, 0, 0])

W  D  L  Pts
England        2  1  1    7
United States  1  2  1    5
Iran           1  0  3    3
Wales          0  1  3    1